import PGNOImg from '@/components/resume_sections/experience/pgno.webp';
import PanasiaticImg from '@/components/resume_sections/experience/panasiatic.webp';
import ConcentrixImg from '@/components/resume_sections/experience/concentrix.webp';
import FreelanceImg from '@/components/resume_sections/experience/freelance.webp';
import MobileLegendsImg from '@/components/resume_sections/experience/mobile-legends.webp';

export const EXPERIENCES = [
  /*{
    step: 1,
    company: 'Concentrix - Mediacom',
    logo: ConcentrixImg,
    logoInitials: 'CNX',
    employmentType: 'Full-time · On-site',
    durationMonths: '',
    location: 'Bacolod, Negros Occidental, Philippines',
    workMode: 'On-site',
    role: 'Advisor II, Customer Service',
    dateRange: 'Oct 2026 – Present',
    description: 'Deliver technical support and customer assistance for Mediacom telecommunications services, encompassing troubleshooting of internet connectivity, cable television, and phone service issues. Resolve technical problems efficiently while ensuring optimal customer satisfaction and service quality.',
    skills: [
      'Technical Support',
      'Telecommunications Support',
      'Internet Troubleshooting',
      'Cable Services',
      'Phone Services',
      'Customer Service',
      'Problem Resolution',
      'Billing Support',
      'Issue Escalation',
      'Customer Communication',
    ],
  },*/
  {
    step: 1,
    company: 'Freelance',
    logo: FreelanceImg,
    logoInitials: 'FL',
    employmentType: 'Part-time · Remote',
    durationMonths: '',
    location: 'Bacolod, Negros Occidental, Philippines',
    workMode: 'Remote',
    role: 'Software Developer',
    dateRange: 'Jul 2026 – Present · 3 mos',
    description: 'Develop and deliver custom web solutions for clients primarily within the regional market, including web applications, responsive websites, and interactive digital experiences. Leverage modern technologies to build scalable, user-focused solutions while managing client relationships and project timelines.',
    skills: [
      'Software Development',
      'Web Development',
      'Frontend Development',
      'Backend Development',
      'API Development',
      'Database Management',
      'UI Development',
      'System Integration',
      'Application Deployment',
      'Technical Troubleshooting',
    ],
  },
  {
    step: 2,
    company: 'PGNO – GSO, Property Management Division',
    logo: PGNOImg,
    logoInitials: 'PGNO',
    employmentType: 'Internship · On-site',
    durationMonths: '',
    location: 'Bacolod, Negros Occidental, Philippines',
    workMode: 'On-site',
    role: 'Software Developer / IT Operations Support Intern',
    dateRange: 'Feb 2026 – May 2026 · 4 mos',
    description: 'Enhanced, deployed, and maintained a lot allocation and property monitoring system used by government office personnel. Performed database schema revisions, data migration, system deployment, and server management while supporting interactive property mapping, document management, Excel reporting, real-time dashboards, and role-based access control. Used GIS software to plot property boundaries, export them as GeoJSON, and upload the files into the system for map visualization. Provided technical support for access issues, data discrepancies, system errors, and hardware problems, while documenting recurring issues and resolutions for ongoing system maintenance.',
    skills: [
      'Software Development',    
      'PHP & MySQL',
      'Database Management',
      'Schema Revision',
      'Data Migration',
      'GIS Mapping',
      'GeoJSON Mapping',
      'System Deployment',
      'Server Management',
      'Hardware Troubleshooting',
      'Technical Support',
      'System Troubleshooting',
    ],

  },
  {
    step: 3,
    company: 'Panasiatic Solutions - Straight Talk',
    logo: PanasiaticImg,
    logoInitials: 'PSST',
    employmentType: 'Full-time · On-site',
    durationMonths: '',
    location: 'Bacolod, Negros Occidental, Philippines',
    workMode: 'On-site',
    role: 'Customer Service Representative',
    dateRange: 'Jul 2024 – Aug 2024 · 2 mos',
    description: 'Delivered customer support and technical troubleshooting for a U.S. prepaid wireless telecommunications account, assisting customers with billing inquiries, account activation, and device connectivity issues. Maintained clear and professional communication to resolve inquiries efficiently within a fast-paced, queue-based contact center environment.',
    skills: [
      'Customer Service',
      'Telecommunications Support',
      'Mobile Support',
      'Account Management',
      'Billing Support',
      'Technical Troubleshooting',
      'Problem Resolution',
      'Customer Communication',
      'Issue Escalation',
      'CRM Systems',
    ],
  },
];
